# Generated by Django 5.2.4 on 2025-07-14 13:42

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.IntegerField(unique=True)),
                ('investment_goal', models.CharField(choices=[('select_your_primary_goal', 'Select Your Primary Goal'), ('retirement_planning', 'Retirement Planning'), ('wealth_building', 'Wealth Building'), ('education_funding', 'Education Funding'), ('education_funding', 'Education Funding'), ('home_purchase', 'Home Purchase'), ('general_investing', 'General Investing')], default='select_your_primary_goal', max_length=50)),
                ('risk_tolerance', models.CharField(choices=[('select_your_risk_tolerance', 'Select Your Risk Tolerance'), ('conservative_low_risk', 'Conservative - Low Risk'), ('moderate_balanced_risk', 'Moderate - Balance Risk'), ('aggressive_high_risk', 'Aggressive - High Risk')], default='select_your_risk_tolerance', max_length=50)),
                ('account_type', models.CharField(choices=[('choose_account_type', 'Choose Account Type'), ('starter_plan', 'Starter Plan'), ('silver_plan', 'Silver Plan'), ('gold_plan', 'Gold Plan')], default='choose_account_type', max_length=50)),
                ('choose_trades', models.CharField(choices=[('crypto', 'Crypto'), ('crude', 'Crude'), ('gold', 'Gold'), ('stock', 'Stock'), ('cfd', 'CFD'), ('fx', 'FX')], max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
