# Generated by Django 5.2.4 on 2025-07-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiconf', '0003_finances'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='doc_type',
            field=models.CharField(choices=[('passport', 'Passport'), ('drivers_license', "Driver's license"), ('national_id', 'National ID')], default='passport', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kyc_photo',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_photos/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kyc_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
