# Generated by Django 5.2.4 on 2025-07-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiconf', '0005_recenttransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recenttransaction',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='recenttransaction',
            name='crypto_type',
        ),
        migrations.RemoveField(
            model_name='recenttransaction',
            name='transaction_status',
        ),
        migrations.RemoveField(
            model_name='recenttransaction',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='recenttransaction',
            name='currency',
            field=models.CharField(choices=[('btc', 'BTC'), ('eth', 'ETH'), ('sol', 'SOL'), ('trc20', 'TRC20'), ('crd', 'CRD')], default='btc', max_length=10),
        ),
        migrations.AddField(
            model_name='recenttransaction',
            name='network',
            field=models.CharField(choices=[('bitcoin', 'Bitcoin'), ('ethereum', 'Ethereum'), ('solana', 'Solana'), ('tron', 'TRC'), ('cardono', 'Cardono')], default='bitcoin', max_length=10),
        ),
        migrations.AddField(
            model_name='recenttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='recenttransaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], default='deposit', max_length=10),
        ),
    ]
