# Generated by Django 5.2.4 on 2025-07-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiconf', '0007_remove_customuser_doc_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kyc',
            old_name='status',
            new_name='kyc_status',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='id_back',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='id_front',
        ),
        migrations.AddField(
            model_name='kyc',
            name='id_back_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='id_front_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
