# Generated by Django 5.2.4 on 2025-07-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiconf', '0008_rename_status_kyc_kyc_status_remove_kyc_id_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='kyc_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='in_review', max_length=20),
        ),
    ]
