# Generated by Django 5.2.4 on 2025-07-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiconf', '0009_alter_kyc_kyc_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
    ]
